"""empty message

Revision ID: 3fb845e08a43
Revises: 
Create Date: 2020-07-03 01:21:47.925498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb845e08a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('discount', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('restaurant',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('restaurant')
    op.drop_table('coupons')
    # ### end Alembic commands ###
