"""empty message

Revision ID: d0c75f0798cf
Revises: 
Create Date: 2020-07-27 19:34:27.319578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c75f0798cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('employee',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('points',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('redeemed_coupons',
    sa.Column('rcid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rcid')
    )
    op.create_table('restaurant',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('restaurant')
    op.drop_table('redeemed_coupons')
    op.drop_table('points')
    op.drop_table('employee')
    op.drop_table('coupons')
    # ### end Alembic commands ###
